# This is a basic workflow to help you get started with Actions

name: Production Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup PHP environment
        # You may pin to the exact commit or the version.
        # uses: nanasess/setup-php@91ce150aeacfb1b2d935e7abf419bfc37244a76c
        uses: nanasess/setup-php@v3.0.6
        with:
          # Version Spec of the version to use.  Examples: 7.1
          php-version: 8.0

      - name: Install Composer packages
        run: composer install --prefer-dist --no-autoloader --no-progress

      - name: Validate Composer packages
        run: composer validate

      - name: Install NPM packages
        run: npm i
      
      - name: Create production build for frontend
        run: npm run prod
